fika-dev/fika-cli

plug_in/git_platform/git_hub/index.ts
src/domain/value_object/exceptions/gh_cli_not_loggedin.ts

Notion Document: https://www.notion.so/Fika-add-GH_CLI_NOT_LOGGEDIN-error-handling-41fa8c0d20da4b4eb923f89a5967757b

[Fika] add GH_CLI_NOT_LOGGEDIN error handling

---

src/domain/service/config.service.ts
src/domain/value_object/exceptions/notion_not_connected.ts

Notion Document: https://www.notion.so/Fika-add-NOTION_NOT_CONNECTED-error-handling-584bf3cea16d480784c3b581d273008b

[Fika] add NOTION_NOT_CONNECTED error handling

---

src/domain/service/message.service.ts

Notion Document: https://www.notion.so/Fika-fix-cpr-message-75a0d4ca053f44e397e6be68e3717cdb

[Fika] fix cpr message

---

package.json
src/command/create/create-issue.action.ts
src/command/create/create-pr.action.ts
src/command/set/set.action.ts
src/domain/service/config.service.ts
src/domain/service/connnect.service.ts
src/domain/service/i_config.service.ts
src/domain/service/i_connect.service.ts
src/domain/value_object/exceptions/base_exception.ts
src/domain/value_object/exceptions/gh_cli_not_loggedin.ts
src/domain/value_object/exceptions/no_gh_cli.ts
src/domain/value_object/exceptions/notion_not_connected.ts
src/domain/value_object/exceptions/wrong_uri.ts
src/domain/value_object/exceptions/wrong_uuid.ts
src/domain/value_object/notion_url.vo.ts
src/domain/value_object/uuid.vo.ts
yarn.lock

Notion Document: https://www.notion.so/Fika-add-WRONG_ARGUMENT-exception-ad8ccc3af5574967b7f95616f31504b1

[Fika] add WRONG_ARGUMENT exception

---

src/domain/service/connnect.service.ts
src/domain/value_object/exceptions/wrong_property_title_name.ts

Notion Document: https://www.notion.so/Fika-add-WRONG_PROPERTY_NAME-handling-27a83eaf74ae497fbf98e58493b71d50

[Fika] add WRONG_PROPERTY_NAME handling

---

src/config/constants/identifiers.ts
src/config/ioc_config.ts
src/domain/service/error_handling.service.ts
src/domain/service/i_error_handling.service.ts
src/domain/service/i_message.service.ts
src/domain/service/message.service.ts
src/index.ts

Notion Document: https://www.notion.so/Fika-fika-cli-add-global-error-handling-7ad063e77d4546cda5584f239df4ecfd

[Fika] fika-cli add global error handling

---

src/domain/service/error_handling.service.ts
src/domain/value_object/exceptions/unknown_error.ts
src/index.ts

Notion Document: https://www.notion.so/Fika-fika-cli-error-handling-5058215cb75f45658599e036307928e5

[Fika] fika-cli error handling 이후 버젼에 대한 디버깅

---

src/domain/service/config.service.ts
src/domain/service/snapshot.service.ts

Notion Document: https://www.notion.so/Fika-fika-config-json-prettify-73424f761e7743bc99caa2159094d904
[Notion 에서 열기](notion://www.notion.so/Fika-fika-config-json-prettify-73424f761e7743bc99caa2159094d904)

[Fika] fika.config.json 파일 저장시 prettify 하기

---

src/domain/service/message.service.ts

Notion Document: https://www.notion.so/Fika-create-PR-base-branch-checkout-pull-message-fb5569e89b48448d98687b5d1dae5767
[Notion 에서 열기](notion://www.notion.so/Fika-create-PR-base-branch-checkout-pull-message-fb5569e89b48448d98687b5d1dae5767)

[Fika] create PR 이후에 base branch 로 checkout 하고 pull 받도록 하는 message

---

plug_in/git_platform/git_hub/index.ts

Notion Document: https://www.notion.so/Fika-PR-issue-8b62abba69b445dea3a54c1dfe270eb7
해결이슈: #94

[Fika] PR 을 만들때, issue 를 연결 시키기

---

package.json
plug_in/git_platform/git_hub/index.ts
src/command/connect/connect.action.ts
src/command/create/create-issue.action.ts
src/command/create/create-pr.action.ts
src/command/set/set.action.ts
src/domain/entity/git_platform.entity.ts
src/domain/entity/i_git_platform.service.ts
src/domain/service/git_platform.service.ts
src/domain/service/i_message.service.ts
src/domain/service/message.service.ts
yarn.lock

Notion Document: https://www.notion.so/Fika-message-service-text-e-g-color-bd397f404e9142bfbdb0eb16744f75be
해결이슈: #96

[Fika] message service 에서 보여주는 text 들을 더 보기 좋게 만들기 (e.g. color)

---

package.json
src/config/constants/uri.ts
src/domain/service/connnect.service.ts

Notion Document: https://www.notion.so/Fika-fika-cli-endpoint-fikadev-com-4ed65517ad5349e1aed7ec7097b278d3
해결이슈: #105

[Fika] fika-cli 의 endpoint 들 fikadev.com 으로 변경하기

---

package.json
plug_in/git_platform/git_hub/index.ts
src/config/constants/uri.ts
src/domain/service/connnect.service.ts
src/index.ts

Notion Document: https://www.notion.so/Fika-debug-label-base-push-b36d1086313a44fcb1d0b132abfd1567
해결이슈: #107

[Fika] debug label 이 있을때, base 브랜치로 push 가 안되는 에러

---

package.json
src/domain/service/i-prompt.service.ts
src/domain/service/prompt.service.ts
yarn.lock

Notion Document: https://www.notion.so/Fika-cli-prompt-service-8d1c053e9ace4d4499ecab91a28f5a09
해결이슈: #111

[Fika] [cli] prompt service 구현

---

src/config/constants/default_config.ts
src/domain/entity/config.entity.ts
src/domain/service/config.service.ts
src/domain/service/i_config.service.ts
src/domain/value_object/fika-token.vo.ts

Notion Document: https://www.notion.so/Fika-cli-config-service-token-method-47f200c7fe5a46bc9eac3cc564c3a65b
해결이슈: #113

[Fika][cli] config service token 관련 method 구현

---

src/domain/service/connnect.service.ts
src/domain/service/i_connect.service.ts

Notion Document: https://www.notion.so/Fika-cli-connect-service-login-method-b1950d52bb9443d4b4bb1b26a08652c5
해결이슈: #115

[Fika] [cli] connect service login 관련 method 구현

---

src/command/auth/signup.action.ts
src/config/constants/identifiers.ts
src/config/ioc_config.ts
src/domain/service/i-prompt.service.ts
src/domain/service/prompt.service.ts

Notion Document: https://www.notion.so/Fika-cli-signup-action-fa6fe43ed3cb4311a5408521a5ef8898
해결이슈: #117

[Fika] [cli] signup action 구현

---

src/command/auth/login.action.ts

Notion Document: https://www.notion.so/Fika-cli-login-action-29a7955b58024329a1ff3c3a1b9c8163
해결이슈: #119

[Fika][cli] login action 구현

---

src/command/auth/auth-handler.ts
src/command/connect/index.ts
src/command/create/index.ts
src/command/error/error_handlers.ts
src/command/set/index.ts
src/command/wrapper/wrappers.ts

Notion Document: https://www.notion.so/Fika-cli-auth-handler-abc757c768c6477bb73366aa9447f625
해결이슈: #121

[Fika][cli] auth handler 구현

---

src/command/auth/auth-handler.ts
test/command/analyze/analyze.action.test.ts
test/command/auth/signup.action.test.ts
test/command/push/push.action.test.ts
test/command/set/set.action.test.ts

Notion Document: https://www.notion.so/Fika-auth-03aaf3e03de24f1d8aaf332ac2be271f
해결이슈: #125

[Fika] auth 관련 테스트 코드 작성

---

src/domain/service/connnect.service.ts

Notion Document: https://www.notion.so/Fika-debug-isAvailableEmail-error-code-error-17f45b469b93442fb683141c61e997c7
해결이슈: #127

[Fika] [debug] isAvailableEmail error code 매칭 안되는 error

---

src/command/auth/signup.action.ts
src/domain/service/i_message.service.ts
src/domain/service/message.service.ts

Notion Document: https://www.notion.so/Fika-invalid-email-b26b3a0e3ce04461b48ba0866c3085d9
해결이슈: #129

[Fika] invalid email 일때 알림 처리

---

package.json
src/config/constants/identifiers.ts
src/config/constants/uri.ts
src/config/ioc_config.ts
src/domain/service/connnect.service.ts

Notion Document: https://www.notion.so/Fika-test-server-fika-cli-test-test-server-291a6945e58c4192b90c9c15bf1b49a8
해결이슈: #131

[Fika] test server 를 갖추고, fika-cli 의 test 를 수행할때, test server 와 연동되도록 하기.

---

src/command/auth/auth-handler.ts
src/command/connect/index.ts
src/command/create/index.ts
src/command/error/error_handlers.ts
src/command/set/index.ts
src/command/wrapper/wrappers.ts
src/domain/service/config.service.ts
src/domain/service/error_handling.service.ts
src/domain/value_object/exceptions/not_authenticated.ts

Notion Document: https://www.notion.so/Fika-async-wrapper-51c43d891b79444488a1405bd3a5337d
해결이슈: #133

[Fika] async wrapper 디버깅

---

src/command/analyze/analyze.action.ts
src/command/auth/auth-handler.ts
src/command/create/create-issue.action.ts
src/command/create/create-pr.action.ts
src/command/init/init.action.ts
src/config/constants/identifiers.ts
src/config/ioc_config.ts
src/domain/service/config.service.ts
src/domain/service/i_config.service.ts
test/command/set/set.action.test.ts

Notion Document: https://www.notion.so/Fika-test-fika-path-78ff79f867e4479ea8b081e78dfbbd63
해결이슈: #135

[Fika] test 용 fika path 사용하기

---

plug_in/git_platform/git_hub/index.ts
src/config/ioc_config.ts
src/domain/service/error_handling.service.ts
src/domain/value_object/exceptions/gh_pr_already_exists.ts

Notion Document: https://www.notion.so/Fika-cpr-branch-PR-669a40ff237c47d9a79793fd14451f89
해결이슈: #144

[Fika] cpr 관련 에러 핸들링 (중복된 branch PR)

---

plug_in/git_platform/git_hub/index.ts
src/domain/service/error_handling.service.ts
src/domain/value_object/exceptions/gh_no_commits.ts

Notion Document: https://www.notion.so/Fika-cpr-No-commits-730bc2e965234eaa8206ba2c1fbcb0f9
해결이슈: #146

[Fika] cpr 관련 에러 핸들링 (No commits)

---

src/domain/service/connnect.service.ts

Notion Document: https://www.notion.so/Fika-connection-trial-max-time-442767487234445eaeff16bd38b89d4d
해결이슈: #148

[Fika] connection trial max time 추가하기

---

plug_in/git_platform/git_hub/index.ts
src/command/analyze/analyze.action.ts
src/command/auth/auth-handler.ts
src/command/create/create-issue.action.ts
src/command/create/create-pr.action.ts
src/config/constants/default_config.ts
src/domain/entity/config.entity.ts
src/domain/entity/git_platform.entity.ts
src/domain/service/config.service.ts
src/domain/service/git_platform.service.ts
src/domain/service/i_config.service.ts
src/domain/service/message.service.ts
src/domain/value_object/git_config.vo.ts

Notion Document: https://www.notion.so/Fika-issue-base-branch-name-option-2cddb294ff874515ae12f85d39b0c8a4
해결이슈: #152

[Fika] issue, base branch name 의 형식을 option 으로 바꿀 수 있도록 하기

---

src/command/connect/index.ts
src/command/create/index.ts
src/command/set/index.ts
src/command/update/update-handler.ts
src/command/wrapper/wrappers.ts
src/domain/service/config.service.ts
src/domain/service/connnect.service.ts
src/domain/service/i_config.service.ts
src/domain/service/i_connect.service.ts
src/domain/service/i_message.service.ts
src/domain/service/message.service.ts
src/domain/value_object/update-info.vo.ts
src/index.ts

Notion Document: https://www.notion.so/Fika-major-version-update-a6c52c47e5524b83ad306f4df976d947
해결이슈: #154

[Fika] major version update 에 대한 내용을 확인후 업그레이드 안내하기

---

package.json
src/config/ioc_config.ts
src/domain/service/config.service.ts
src/domain/service/connnect.service.ts

Notion Document: https://www.notion.so/Fika-0-3-0-debugging-7b9a18e9bb8447988293d12e5bb9d1d1
해결이슈: ##164

[Fika] 0.3.0 버젼 debugging 하기

---

package.json
src/config/ioc_config.ts

Notion Document: https://www.notion.so/Fika-NODE_ENV-115e41e5987c4c7892b136ffc302f7a3
해결이슈: ##166

[Fika] NODE_ENV 에 따라 달라지는 것 수정하기

---

package.json
src/command/create/create-pr.action.ts
src/command/create/index.ts
src/domain/entity/i_git_platform.service.ts
src/domain/service/git_platform.service.ts

Notion Document: https://www.notion.so/Fika-cpr-base-branch-option-8ee9b6f4aa4f401c8ad01818814adf5f
해결이슈: ##169

[Fika] cpr 에서 base branch 를 option 으로 넣을 수 있도록 하기.

---

package.json
src/domain/service/connnect.service.ts

Notion Document: https://www.notion.so/Fika-debug-connect-redirect-uri-error-969e246367e1474fbfac880214757c86
해결이슈: ##171

[Fika] [debug] connect redirect uri error

---

src/command/create/create-issue.action.ts
src/command/create/create-pr.action.ts
src/command/create/index.ts
src/domain/entity/i_git_platform.service.ts
src/domain/service/connnect.service.ts
src/domain/service/git_platform.service.ts
src/domain/service/i_connect.service.ts

[Fika] cpr 시에 만약 ci 로 issue 와 notion url 이 연결 되어 있다면, 해당 정보만을 이용하기

---

package.json
src/index.ts

[Fika] 이미 중복된 pr 이 있다면 push 만 하기

---

plug_in/git_platform/git_hub/index.ts

[Fika] [Debug] cpr 이후에 pr message 안에 notion page url 비어있는 문제

---

package.json

Notion 다큐먼트: https://www.notion.so/Fika-backend-create-release-notion-page-3820acde55a74387b1f5b84b8f1d24a4
해결이슈: #192

[Fika] backend > create release notion page

---

src/domain/service/i_message.service.ts
src/domain/service/message.service.ts

Notion 다큐먼트: https://www.notion.so/Fika-implement-release-related-MessageService-methods-23ade05ef62a4e288a85d4ed8cc16d3b
해결이슈: #196

[Fika] implement release related MessageService methods

---

src/domain/service/error_handling.service.ts
src/domain/service/i-prompt.service.ts
src/domain/service/prompt.service.ts
src/domain/value_object/exceptions/wrong_tag_format.ts
src/domain/value_object/version_tag.vo.ts

Notion 다큐먼트: https://www.notion.so/Fika-implement-release-related-PromptService-methods-be065d77b212487894cab3212250089f
해결이슈: #198

[Fika] implement release related PromptService methods

---

src/domain/service/connnect.service.ts
src/domain/service/i_connect.service.ts

Notion 다큐먼트: https://www.notion.so/Fika-implement-release-related-ConnectService-methods-4c2a88593f3c4cb0b94f4fd7f338f976
해결이슈: #200

[Fika] implement release related ConnectService methods

---

src/domain/service/config.service.ts
src/domain/service/i_config.service.ts

Notion 다큐먼트: https://www.notion.so/Fika-implement-release-related-ConfigService-methods-8188d39a4c564298a96a79908c48fc43
해결이슈: #205

[Fika] implement release related ConfigService methods

---

src/command/release/release.action.ts
src/domain/service/connnect.service.ts
src/domain/service/i_connect.service.ts

Notion 다큐먼트: https://www.notion.so/Fika-implement-release-action-f1ca376e317243fc87976faabb39605d
해결이슈: #207

[Fika] implement release action

---

src/command/release/index.ts
src/index.ts

Notion 다큐먼트: https://www.notion.so/Fika-implement-release-command-12fbbf52e12b488e92087f06edcc49de
해결이슈: #209

[Fika] implement release command

---

src/command/release/release.action.ts
src/domain/entity/i_git_platform.service.ts
src/domain/service/git_platform.service.ts

Notion 다큐먼트: https://www.notion.so/Fika-cli-debug-checkoutToBranch-5696f1bea1fa4f99931783f06ff0754a
해결이슈: #213

[Fika] [cli] [debug] checkoutToBranch

---

src/command/create/create-pr.action.ts
src/domain/entity/issue.entity.ts
src/domain/service/connnect.service.ts
src/domain/service/i_connect.service.ts

Notion 다큐먼트: https://www.notion.so/Fika-cli-record-PR-to-server-after-cpr-command-f2a35ed6ba604806bca3aff618817e61
해결이슈: #215

[Fika] [cli] record PR to server after cpr command

---

plug_in/git_platform/git_hub/index.ts
src/command/create/create-issue.action.ts
src/domain/service/error_handling.service.ts
src/domain/service/i_connect.service.ts
src/domain/value_object/exceptions/no_git_remote.vo.ts

Notion 다큐먼트: https://www.notion.so/Fika-remote-repository-set-handling-7ad451fb707444b9b58479ea61bc2240
해결이슈: #230

[Fika] remote repository 가 set 되어 있지 않은 경우 handling

---

src/domain/service/i_connect.service.ts

Notion 다큐먼트: https://www.notion.so/test-test-issue-928db37b4cd84960adb4d3f46e9d4a11
해결이슈: #227

[test] test issue

---

plug_in/git_platform/git_hub/index.ts
src/domain/service/error_handling.service.ts
src/domain/value_object/exceptions/no_base_branch.vo.ts

Notion 다큐먼트: https://www.notion.so/Fika-develop-handling-644cf247d20b443e9ecde9e3682c2850
해결이슈: #229

[Fika] develop 브랜치가 생성이 안되어 있는 경우 handling

---

package.json

Notion 다큐먼트: https://www.notion.so/Fika-issue-handling-5e8067b3924344c8b366fee313e2802e
해결이슈: #233

[Fika] 이미 생성된 issue 정보가 있는 경우의 handling

---

.gitmodules

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-test-test-samples-384aeed8f1b04b128daa4c3ea5e6c0ea
해결이슈: #248

[Fika] test 를 위한 test samples 폴더 삭제

---

jest.config.js
package.json
yarn.lock

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-jest-inversify-conflict-error-890042a743eb48d5894494f61beb99c6
해결이슈: #250

[Fika] jest - inversify conflict error

---

src/command/wrapper/wrappers.ts
src/domain/service/error_handling.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-Debug-authWrapper-undefined-return-handling-a66911e85e404d5c894a34b5463f6fa5
해결이슈: #252

[Fika] [Debug] authWrapper 에서 undefined 가 return 되는 경우에 대한 handling

---

.env
.gitignore
package.json
src/config/ioc_config.ts
src/index.ts
test/test-utils/index.ts
yarn.lock

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-clonning-test-repository-to-given-path-02c60c59ab594e36b6e157bdfbb5f4fb
해결이슈: #257

[Fika] clonning test repository to given path

---

test/command/auth/signup.action.test.ts
test/command/init/init.action.test.ts
test/test-utils/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-remove-errors-of-old-testing-cases-1351a461ffc34347a7d060eb41ae0629
해결이슈: #260

[Fika] remove errors of old testing cases

---

jest.config.js
src/command/create/create-pr.action.test.ts
src/domain/entity/i_git_platform.service.ts
src/domain/service/git_platform.service.ts
test/command/create/create-issue.action.test.ts
test/test-constants/index.ts
test/test-utils/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-build-test-cases-related-to-cpr-b94da3f268fa4b9db8101589f3ad96ad
해결이슈: #271

[Fika] build test cases related to cpr

---

.github/workflows/ci.yaml
.gitignore
src/command/create/create-pr.action.test.ts
test/test-utils/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-github-actions-continuous-testing-18819d95722e42009ef33ee2503a34f9
해결이슈: #275

[Fika] github actions 로 continuous testing 환경 마련하기

---

src/domain/service/connnect.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-Debug-timeout-5-f0acda7ec30b459c81578f67c0128542
해결이슈: #280

[Fika][Debug] timeout 5초 에러

---

src/domain/entity/i_git_platform.service.ts
src/domain/service/git_platform.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-implement-getBranches-method-eaefdcb51aae48559b18c5545272ec58
해결이슈: #282

[Fika] implement getBranches method

---

src/config/constants/default_config.ts
src/config/constants/path.ts
src/domain/service/config.service.ts
src/domain/service/i_config.service.ts
test/command/init/init.action.test.ts
test/test-utils/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-init-action-related-configService-methods-5773e95b64434b5eba1d0466f0c44f6b
해결이슈: #286

[Fika] init action related configService methods

---

src/command/init/init.action.ts
test/command/analyze/analyze.action.test.ts
test/command/init/init.action.test.ts
test/command/push/push.action.test.ts
test/command/set/set.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-clear-out-exsing-init-action-21aa2047f2084a24a65c4dbc30bddd91
해결이슈: #288

[Fika] clear out exsing init action

---

src/command/create/create-pr.action.test.ts
src/command/init/index.ts
src/command/init/init.action.ts
src/config/constants/default_config.ts
src/domain/service/prompt.service.ts
src/index.ts
test/command/init/init.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-cli-implement-new-init-command-bd882c00ad7345e699c4ba31d0afc87d
해결이슈: #290

[Fika] [cli] implement “new” init command

---

src/domain/service/config.service.ts
src/domain/service/i_config.service.ts
test/command/init/init.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-implement-getLocalConfig-method-da1a1f8b9a994ab28ed4b167bb4acdb5
해결이슈: #292

[Fika] implement getLocalConfig method

---

src/domain/service/i-prompt.service.ts
src/domain/service/prompt.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-implement-confirmAction-method-f9bb30323aee43f78461d36b58bae709
해결이슈: #294

[Fika] implement confirmAction method

---

src/domain/entity/i_git_platform.service.ts
src/domain/service/git_platform.service.ts
test/command/start/start.action.test.ts
test/test-utils/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-implement-start-related-gitPlatformService-methods-29b26755aa96431aa6afc2a37e865f6a
해결이슈: #296

[Fika] implement start related gitPlatformService methods

---

.env
package.json
src/command/create/create-pr.action.test.ts
src/command/create/create-pr.action.ts
src/command/start/start.action.ts
src/config/ioc_config.ts
src/domain/service/connnect.service.ts
src/domain/service/git_platform.service.ts
src/domain/service/i_connect.service.ts
src/domain/service/i_message.service.ts
src/domain/service/message.service.ts
test/command/auth/signup.action.test.ts
test/command/create/create-issue.action.test.ts
test/command/init/init.action.test.ts
test/command/start/start.action.test.ts
test/test-constants/index.ts
test/test-utils/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-implement-start-action-fa96692ed7cd4beeaf4aed325baa6054
해결이슈: #298

[Fika] implement start action

---

src/domain/entity/i_git_platform.service.ts
src/domain/service/git_platform.service.ts
test/command/finish/finish.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-implement-checkConflict-method-118027232b1c415e9366d9df9f9973c3
해결이슈: #300

[Fika] implement checkConflict method

---

src/domain/service/git_platform.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-git-english-37b5980afd604a15a4eb688370cf53bb
해결이슈: #305

[Fika] git 실행 언어를 english 로 한정하기

---

src/command/finish/index.ts
src/command/start/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-add-start-finish-command-0fbc63f6ad574055b21016d54ed30446
해결이슈: #307

[Fika] add start, finish command

---

src/actions/checkout-existing-issue.action.ts
src/actions/complex/create-PR.action.ts
src/actions/complex/create-issue.action.ts
src/actions/fika/get-fika-issue.action.ts
src/actions/git/checkout-issue-branch.action.ts
src/actions/git/create-git-platform-PR.action.ts
src/actions/git/create-git-platform-issue.action.ts
src/actions/git/pull-and-check-conflict.action.ts
src/actions/git/pull.action.ts
src/actions/git/stash-unstaged-change.action.ts
src/actions/git/validate-start-branch.action.ts
src/actions/notion/get-existing-issue.action.ts
src/actions/notion/get-notion-issue.action.ts
src/command/finish/finish.action.ts
src/command/start/start.action.ts
src/domain/service/git_platform.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-add-handling-of-no-remote-ref-38f37e6f0a984710a79d897edcaf796c
해결이슈: #309

[Fika] add handling of no remote ref

---

src/command/create/create-pr.action.test.ts
src/command/finish/finish.action.ts
src/command/start/start.action.ts
src/domain/service/i_message.service.ts
src/domain/service/message.service.ts
test/command/create/create-issue.action.test.ts
test/command/finish/finish.action.test.ts
test/command/push/push.action.test.ts
test/command/set/set.action.test.ts
test/service/message.service.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-message-service-05c577cb1b42412c87a3bf6a385ccd74
해결이슈: #312

[Fika] message service 재정비.

---

src/domain/service/prompt.service.ts
test/command/init/init.action.test.ts
test/service/prompt.service.index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-prompt-service-6f7f357103394123948fa8bd978150c4
해결이슈: #316

[Fika] prompt service 가다듬기

---

src/command/finish/finish.action.ts
src/command/start/start.action.ts
src/domain/service/i_message.service.ts
src/domain/service/message.service.ts
test/command/push/push.action.test.ts
test/service/message.service.index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-message-service-readline-process-c0d3167f1db341aa9cef169ab2ca37b1
해결이슈: #319

[Fika] message service readline → process 로 변경하기

---

.fikarc
package.json

Notion 다큐먼트: https://www.notion.so/fikadev/fika-1-0-developer-version-5e10247fee6a4c4c93ac804873da252f
해결이슈: #322

[fika] 0.4.0 에 대한 developer version 출시하기

---

.fikarc
src/config/constants/default_config.ts
src/domain/entity/config.entity.ts
src/domain/service/config.service.ts
src/domain/service/i_config.service.ts
test/test-constants/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-fikarc-issue-branch-933728bd123440038405aa1d7ba9455b
해결이슈: #324

[Fika] fikarc 파일에 issue branch 패턴 넣기

---

.fikarc
package.json
src/command/init/init.action.ts
src/config/constants/uri.ts
src/config/ioc_config.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-domain-config-error-handling-4f633e5ea2c84032b41eec99dfe282df
해결이슈: #327

[Fika] domain config 관련 error handling

---

src/domain/service/connnect.service.ts
src/domain/service/error_handling.service.ts
src/domain/value_object/exceptions/notion_page_not_found.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-error-handling-Notion-document-4bf4adcda59145c88bf8a8b9717d4ab9
해결이슈: #326

[Fika] [error handling] 특정 Notion document 를 찾을 수 없을 때

---

package.json
src/domain/service/error_handling.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-cpr-pull-request-push-464768fb26494ceb880a553bfd62dfe4
해결이슈: #330

[Fika] cpr 시에 이미 올라가 있는 pull request 가 있을 경우, push 하기

---

src/actions/git/checkout-base-branch.action.ts
src/command/finish/finish.action.ts
test/command/finish/finish.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-cli-make-it-optional-checkouting-to-develop-branch-after-fika-finish-85ce5cd0d8ef4201b462cd583994ef38
해결이슈: #332

[Fika][cli] make it optional checkouting to develop branch after “fika finish”

---

src/command/checkout-develop/checkout-develop-branch.action.ts
src/command/checkout-develop/index.ts
test/command/checkout-developp-branch/checkout-develop-branch.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-cli-make-a-simple-command-checking-out-to-develop-branch-7b5247d369f64d3eadb9aa2c09fda822
해결이슈: #334

[Fika][cli] make a simple command checking out to develop branch 

---

src/command/checkout-feature-branch/checkout-feature-branch.action.ts
src/command/checkout-feature-branch/index.ts
src/domain/entity/i_git_platform.service.ts
src/domain/service/git_platform.service.ts
test/command/checkout-feature-branch/checkout-feature-branch.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-cli-checking-out-to-recent-feature-branch-83c052d11c044cedbcbc5d8f89819216
해결이슈: #336

[Fika][cli] checking out to recent feature branch

---

src/command/init/init.action.ts
src/domain/entity/i_git_platform.service.ts
src/domain/service/config.service.ts
src/domain/service/git_platform.service.ts
test/command/init/init.action.test.ts
test/test-utils/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-cli-during-fika-init-if-there-is-not-branches-configured-make-them-90d4187697214beaa9c1ee489edfdd55
해결이슈: #340

[Fika][cli] during fika “init” if there is not branches configured make them

---

src/command/info/index.ts
src/command/info/info.action.ts
test/command/info/info.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-branch-notion-page-github-page-print-0f4b1fc3014b4704ae1101e9c21cca02
해결이슈: #342

[Fika] 특정 branch 에서 관련된 notion page, github page 정보 print 하기

---

package.json
src/command/checkout-develop/index.ts
src/command/info/index.ts
src/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-cli-no-commands-error-for-info-f-b-347eebf2b87247258e998998544e1e2a
해결이슈: #344

[Fika][cli] no commands error for info, f, b

---

src/command/checkout-develop/index.ts
src/command/info/index.ts
test/command/info/info.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-cli-fika-info-401-error-49177246f53f441f8a20e4f6cbc5dfff
해결이슈: #346

[Fika][cli] fika info 401 error

---

package.json
src/domain/service/git_platform.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-LC_ALL-option-error-in-windows-253be3a08e1b4cbd99327e5b38dcb42c
해결이슈: #349

[Fika] LC_ALL option error in windows

---

package.json
src/domain/service/git_platform.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-fika-d-command-create-branch-named-develop-error-36acd6d930f8476e83d0c0a3ee1b67b8
해결이슈: #351

[Fika] “fika d” command create branch named “develop;” error

---

package.json
src/domain/service/git_platform.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-cli-checking-remote-url-not-working-error-b57a5d6ad5af41c0aafb6eab9aaaeabe
해결이슈: #359

[Fika][cli] checking remote url not working error

---

.github/workflows/ci.yaml
.prettierrc
package.json
src/config/ioc_config.ts
src/domain/service/git_platform.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-cli-add-windows-testing-environment-fd11682f7bed4ed18be40066354c5f71
해결이슈: #356

[Fika][cli] add windows testing environment

---

src/command/init/init.action.ts
src/domain/service/git_platform.service.ts
test/command/init/init.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fix-the-remote-url-request-inside-fika-init-99620b432339440ba1c41ef27de5a29d
해결이슈: #361

Fix the remote url request inside fika init

---

test/service/git_platform.service.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-check-if-there-is-some-changes-or-not-before-commiting-1603f0612da242c1be78b3b14d0494e1
해결이슈: #364

[fika-cli] check if there is some changes or not before commiting 

---

src/actions/git/pull-and-check-conflict.action.ts
src/actions/git/pull.action.ts
src/command/pull/index.ts
src/command/pull/pull.action.ts
src/domain/entity/i_git_platform.service.ts
src/domain/service/git_platform.service.ts
src/index.ts
test/command/pull/pull.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-add-fika-pull-4030750cb15b47d0868e66d113543932
해결이슈: #371

[Fika] add “fika pull”

---

test/command/finish/finish.action.jira.test.ts
test/command/set/set.action.test.ts
test/command/start/start.action.jira.test.ts
test/test-constants/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-cli-update-to-handle-jira-issue-part-ad9e92570312474d9a919fbdb87ff42a
해결이슈: #366

[Fika] [cli] update to handle jira issue part

---

src/command/checkout-feature-branch/checkout-feature-branch.action.ts
src/command/checkout-feature-branch/index.ts
src/domain/entity/i_git_platform.service.ts
src/domain/service/error_handling.service.ts
src/domain/service/git_platform.service.ts
src/domain/value_object/exceptions/no_remote_branch.ts
test/command/checkout-feature-branch/checkout-feature-branch.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/Fika-checkout-to-branch-using-issueNumber-f3b44739b3914e679a648f40b5c0879e
해결이슈: #375

[Fika] checkout to branch using issueNumber

---

README.md

Notion 다큐먼트: https://www.notion.so/fikadev/doc-git-README-upgrade-ab2fb679977b42c7ac3fbb08cad50d5f
해결이슈: #387

[doc] git README upgrade

---

plug_in/workspace_platform/jira/index.ts
plug_in/workspace_platform/notion/index.ts
src/command/connect/connect.action.ts
src/domain/entity/add_on/workspace_platform.entity.ts
src/domain/service/connnect.service.ts
src/domain/service/i_connect.service.ts
test/command/connect/connect.action.test.ts
test/test-constants/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-add-state-to-callback-url-aded0f904a47474dbde0c60ef853befb
해결이슈: #391

[fika-cli] add state to callback url

---

plug_in/workspace_platform/notion/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-fix-notion-callback-uri-7c8b9609f7c846e8b50443a14a74c011
해결이슈: #396

[fika-cli] [fix] notion callback uri

---

src/command/checkout-feature-branch/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-fika-f-error-9dc9f03c0c9c475cb0c9d150f0fabe7d
해결이슈: #398

[fika-cli] fika f error

---

src/actions/git/stash-unstaged-change.action.ts
src/domain/service/error_handling.service.ts
src/domain/value_object/exceptions/user_stopped.ts
test/command/start/start.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-error-during-fika-start-There-is-unstaged-changes-question-not-awaiting-735ac3dec9c24179bc98c1a8fab85da3
해결이슈: #400

[fika-cli] [error] during “fika start” ? There is unstaged changes. question not awaiting

---

package.json
src/command/connect/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-fika-connect-argument-warning-317016efdbbb460c8aab25cf934d4e95
해결이슈: #403

[fika-cli] fika connect 에서 argument 가 없으면 warning

---

package.json
src/actions/git/pull-and-check-conflict.action.ts
src/domain/service/error_handling.service.ts
src/domain/service/git_platform.service.ts
src/domain/value_object/exceptions/git_error.ts
test/command/finish/finish.action.test.ts
test/command/start/start.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-fika-finish-stop-action-if-conflict-exist-9c59a49387464b9092c31f2fc3626517
해결이슈: #405

[fika-cli] “fika finish” stop action if conflict exist

---

package.json
src/actions/complex/create-PR.action.ts
src/actions/complex/create-issue.action.ts
src/actions/git/checkout-issue-branch.action.ts
src/domain/entity/issue.entity.ts
src/domain/service/connnect.service.ts
src/domain/service/i_connect.service.ts
src/infrastructure/dto/create_issue_record.dto.ts
test/command/info/info.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-fika-be-save-branch-name-to-issue-record-a6fad4743cc04c338d15c482483658ce
해결이슈: #411

[fika-cli], [fika-be] save branch name to issue record

---

src/command/checkout-feature-branch/checkout-feature-branch.action.ts
src/domain/context/context.functions.ts
src/domain/context/context.types.ts
src/domain/context/git-context/git-context.types.ts
src/domain/context/how-to-check.values.ts
src/domain/general/general.types.ts
src/domain/git-command/command.functions.ts
src/domain/git-command/command.types.ts
src/domain/git-command/git-command.values.ts
src/domain/git-command/parser/parser.functions.ts
src/domain/rules/rule.types.ts
src/domain/rules/validation-rules/validation-rules.functions.ts
src/infrastructure/services/implementation/commander.service.ts
src/infrastructure/services/interface/i_commander.service.ts
test/domain/context/context.functions.test.ts
test/domain/rules/validation-rules/validation-rules.functions.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-add-check-context-function-rule-functions-7e2c648fb1b340619682db1781319ae2
해결이슈: #420

[fika-cli] add check context function & rule functions

---

src/domain/command/command.values.ts
src/domain/context/cmd-context/cmd-context.types.ts
src/domain/context/context.types.ts
src/domain/context/git-context/git-context.types.ts
src/domain/context/how-to-check.values.ts
src/domain/git-command/command.types.ts
src/domain/git-command/parser/parser.functions.ts
src/domain/git-command/parser/parser.values.ts
test/domain/git-command/parser/parser.functions.test.ts
test/test-constants/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-check-rules-for-cmd-and-context-1efa1da7efb84525b434bc9562346d9a
해결이슈: #424

[fika-cli] check rules for cmd and context

---

src/domain/context/how-to-check.values.ts
src/domain/git-command/command.functions.ts
src/domain/git-command/command.types.ts
src/domain/git-command/git-command.values.ts
src/domain/service/i_git_platform.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-prepare-command-values-to-replace-gitplatform-service-dbe89d1efb1549ca98191ab096a32e90
해결이슈: #427

[fika-cli] prepare command values to replace gitplatform service

---

src/command/checkout-feature-branch/checkout-feature-branch.action.ts
src/config/constants/default_config.ts
src/config/constants/identifiers.ts
src/config/ioc_config.ts
src/domain/context/context.functions.ts
src/domain/context/how-to-check.values.ts
src/domain/git-command/command.functions.ts
src/domain/git-command/command.types.ts
src/domain/git-command/git-command.values.ts
src/domain/git-command/parser/parser.functions.ts
src/domain/git-command/parser/parser.values.ts
src/domain/rules/rule.functions.ts
src/domain/rules/validation-rules/validate.functions.ts
src/domain/rules/validation-rules/validation-rules.functions.ts
src/domain/service/config.service.ts
src/domain/service/git_platform.service.ts
src/domain/value_object/git_config.vo.ts
src/infrastructure/services/implementation/commander.service.ts
src/infrastructure/services/interface/i_commander.service.ts
test/command/checkout-feature-branch/checkout-feature-branch.action.test.ts
test/domain/git-command/command.functions.test.ts
test/test-constants/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-create-checkoutToFeatureBranch-for-command-function-e56efc64314f43fbbe2754f3946ad961
해결이슈: #430

[fika-cli] create checkoutToFeatureBranch for command function

---

src/domain/service/connnect.service.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-fix-git-repo-problem-issue-f142dd2ba1d24d099cb366830e4c6f0f
해결이슈: #432

[fika-cli] fix git repo problem issue

---

src/command/checkout-feature-branch/checkout-feature-branch.action.ts
src/domain/git-command/command.functions.ts
test/command/checkout-feature-branch/checkout-feature-branch.action.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-add-no-branchName-handling-to-checkout-feature-branch-6842f68e9cd3485f9dd7faa5aba5ef59
해결이슈: #434

[fika-cli] add no branchName handling to checkout feature branch 

---

src/command/error/error_handlers.ts
src/infrastructure/services/implementation/commander.service.ts
test/domain/rules/validation-rules/validation-rules.functions.test.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-fix-checkout-error-d398c13d30564b9fab4ae4e23a99f7f8
해결이슈: #443

[fika-cli] fix checkout error

---

src/actions/complex/checkout-depending-on-config.action.ts
src/actions/complex/create-PR.action.ts
src/actions/fika/get-fika-issue.action.ts
src/actions/git/checkout-base-branch.action.ts
src/actions/git/create-git-platform-PR.action.ts
src/command/finish/finish.action.ts
src/config/constants/messages.ts
src/domain/git-command/command.functions.ts
test/command/finish/finish.action.test.ts
test/test-constants/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-refactor-finish-action-e483857aa2534ac6a71d02192589b83e
해결이슈: #442

[fika-cli] refactor finish action

---

src/actions/fika/get-fika-issue.action.ts
src/actions/git/ask-to-continue-with-uncommited-changes.action.ts
src/actions/git/git-pull.action.ts
src/command/error/error_handlers.ts
src/domain/general/general.types.ts
src/domain/git-command/command.functions.ts
src/domain/git-command/parser/parser.functions.ts
src/domain/rules/validation-rules/validate.functions.ts
src/domain/rules/validation-rules/validation-rule.types.ts
src/domain/service/error_handling.service.ts
src/domain/service/i_error_handling.service.ts
test/command/finish/finish.action.test.ts
test/command/pull/pull.action.test.ts
test/command/start/start.action.test.ts
test/domain/context/context.functions.test.ts
test/domain/git-command/command.functions.test.ts
test/domain/git-command/parser/parser.functions.test.ts
test/domain/rules/validation-rules/validate.function.test.ts
test/domain/rules/validation-rules/validation-rules.functions.test.ts
test/service/error-handling.service.test.ts
test/test-constants/index.ts

Notion 다큐먼트: https://www.notion.so/fikadev/fika-cli-refactor-error-handling-7912b62985e143f8af3c652ef6b7a69e
해결이슈: #447

[fika-cli] refactor error handling
